### ISSUE TITLE
Development Update

### ISSUE THREAD

**Issue by jandayanan** [josebalius/react-grid#6]
Hi.

I would like to ask whether or not the development for this repo is still continued?

Thanks,

Jan

**Comment by josebalius** [comment]
@jandayanan I have lots of code to commit, unfortunately it's still buried inside an active project right now. I'll try to find some time soon to publish it.

**Comment by deifos** [comment]
Hi Jose, Is this project still alive? I know is been a while but, the idea sounds promising.

Thanks!

**Comment by josebalius** [comment]
@deifos It's been a while since I looked at anything for this, sorry :/ if you have any ideas or want to work on it, more than happy to make you a contributor and/or transfer the project.

There are already some high quality react projects that deal with large lists, mainly: https://bvaughn.github.io/react-virtualized/#/components/List and a few other
